#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
ynh_config_add_systemd --service="${app}-web" --template="deluge-web.service"

yunohost service add $app --description="Lightweight BitTorrent client" --log="/var/log/$app/$app.log"
yunohost service add ${app}-web --description="BitTorrent UI" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

mkdir -p /var/log/$app

#chown -R $app:$app /var/log/$app
#chmod -R 750 /var/log/$app

#chown -R $app:www-data "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start"

ynh_systemctl --service=${app}-web --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
