#!/bin/bash



source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
ynh_restore "/etc/systemd/system/${app}-web.service"
systemctl enable $app.service --quiet
systemctl enable ${app}-web.service --quiet

yunohost service add $app --description="Lightweight BitTorrent client" --log="/var/log/$app/$app.log"
yunohost service add ${app}-web --description="BitTorrent UI" --log=/var/log/$app/$app.log

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

# Typically you only have either $app or php-fpm but not both at the same time...
ynh_systemctl --service=$app --action="start"

ynh_systemctl --service=${app}-web --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
